import { exec } from 'dugite'
import { createHash } from 'crypto'
import {
  chmod,
  mkdir,
  readFile,
  readdir,
  rename,
  rm,
  writeFile,
} from 'fs/promises'
import { join } from 'path'

import {
  GitHookType,
  HookLoadout,
  HookScript,
  InstalledScriptStatus,
} from './loadout-types'
import { pathExists } from '../path-exists'

const DISPATCHER_MARKER = '# Auto-generated by Madness Desktop'

/**
 * Returns the thin dispatcher script for a given hook type.
 * The dispatcher runs all executable *.sh scripts in the hook's .d/ directory.
 */
export function getDispatcherScript(hookType: GitHookType): string {
  return `#!/usr/bin/env bash
${DISPATCHER_MARKER} — do not edit
DIR="$(cd "$(dirname "$0")/${hookType}.d" 2>/dev/null && pwd)"
[[ -d "$DIR" ]] || exit 0
for script in "$DIR"/*.sh; do
  [[ -x "$script" ]] && "$script" "$@"
done
`
}

/**
 * Install a loadout into a repository.
 *
 * Creates .githooks/ with dispatcher scripts and .d/ subdirectories
 * containing the individual hook scripts, then sets core.hooksPath.
 */
export async function installLoadout(
  repoPath: string,
  loadout: HookLoadout,
  allScripts: ReadonlyArray<HookScript>,
  disabledScripts: ReadonlyArray<string> = []
): Promise<Record<string, string>> {
  const hashes: Record<string, string> = {}
  const hooksDir = join(repoPath, '.githooks')
  await mkdir(hooksDir, { recursive: true })

  // Resolve which scripts belong to this loadout
  const scripts = loadout.scriptIds
    .map(id => allScripts.find(s => s.id === id))
    .filter((s): s is HookScript => s !== undefined)

  // Group scripts by hook type
  const byType = new Map<GitHookType, HookScript[]>()
  for (const script of scripts) {
    const group = byType.get(script.hookType) ?? []
    group.push(script)
    byType.set(script.hookType, group)
  }

  // Write dispatcher + .d/ scripts for each hook type
  for (const [hookType, hookScripts] of byType) {
    // Write dispatcher
    const dispatcherPath = join(hooksDir, hookType)
    await writeFile(dispatcherPath, getDispatcherScript(hookType), {
      mode: 0o755,
    })

    // Create .d/ directory
    const dDir = join(hooksDir, `${hookType}.d`)
    await mkdir(dDir, { recursive: true })

    // Write individual scripts
    for (const hs of hookScripts) {
      const disabled = disabledScripts.includes(hs.id)
      const filename = disabled ? `${hs.id}.sh.disabled` : `${hs.id}.sh`
      const scriptPath = join(dDir, filename)
      await writeFile(scriptPath, hs.script, { mode: 0o755 })
      hashes[hs.id] = hashScript(hs.script)
    }
  }

  // Set core.hooksPath
  await exec(['config', 'core.hooksPath', '.githooks'], repoPath)
  return hashes
}

/**
 * Uninstall all loadout-managed hooks from a repository.
 *
 * Only removes dispatcher scripts that contain our marker and their .d/
 * directories. Leaves any non-managed hooks untouched.
 */
export async function uninstallLoadout(repoPath: string): Promise<void> {
  const hooksDir = join(repoPath, '.githooks')

  const entries = await readdir(hooksDir, { withFileTypes: true }).catch(
    () => []
  )

  for (const entry of entries) {
    if (entry.isDirectory() && entry.name.endsWith('.d')) {
      await rm(join(hooksDir, entry.name), { recursive: true, force: true })

      // Remove the matching dispatcher if it's ours
      const dispatcherName = entry.name.replace(/\.d$/, '')
      const dispatcherPath = join(hooksDir, dispatcherName)
      try {
        const content = await readFile(dispatcherPath, 'utf8')
        if (content.includes(DISPATCHER_MARKER)) {
          await rm(dispatcherPath, { force: true })
        }
      } catch {
        // dispatcher doesn't exist or unreadable — fine
      }
    }
  }

  // Unset core.hooksPath if it points to .githooks
  const result = await exec(
    ['config', '-z', '--get', 'core.hooksPath'],
    repoPath
  )
  if (result.exitCode === 0 && result.stdout.split('\0')[0] === '.githooks') {
    await exec(['config', '--unset', 'core.hooksPath'], repoPath)
  }
}

/**
 * Toggle a single script within an installed loadout on disk.
 * Renames between .sh and .sh.disabled.
 */
export async function toggleScriptOnDisk(
  repoPath: string,
  script: HookScript,
  enabled: boolean
): Promise<void> {
  const dDir = join(repoPath, '.githooks', `${script.hookType}.d`)
  const enabledPath = join(dDir, `${script.id}.sh`)
  const disabledPath = join(dDir, `${script.id}.sh.disabled`)

  if (enabled) {
    await rename(disabledPath, enabledPath).catch(() => {})
    await chmod(enabledPath, 0o755).catch(() => {})
  } else {
    await rename(enabledPath, disabledPath).catch(() => {})
  }
}

/**
 * Detect which loadout (if any) is installed in a repository by
 * scanning .githooks/ for .d/ directories and matching script files.
 */
export async function detectInstalledScripts(
  repoPath: string
): Promise<ReadonlyArray<{ scriptId: string; enabled: boolean }>> {
  const hooksDir = join(repoPath, '.githooks')
  const results: Array<{ scriptId: string; enabled: boolean }> = []

  const entries = await readdir(hooksDir, { withFileTypes: true }).catch(
    () => []
  )

  for (const entry of entries) {
    if (!entry.isDirectory() || !entry.name.endsWith('.d')) {
      continue
    }

    const dDir = join(hooksDir, entry.name)
    const scripts = await readdir(dDir).catch(() => [])

    for (const file of scripts) {
      if (file.endsWith('.sh')) {
        results.push({ scriptId: file.replace(/\.sh$/, ''), enabled: true })
      } else if (file.endsWith('.sh.disabled')) {
        results.push({
          scriptId: file.replace(/\.sh\.disabled$/, ''),
          enabled: false,
        })
      }
    }
  }

  return results
}

/** sha256 of a script's text, for telling versions apart. */
export function hashScript(text: string): string {
  return createHash('sha256').update(text).digest('hex')
}

/**
 * Compare an installed script with the built-in version.
 *
 * - `current`: the file matches the built-in script.
 * - `outdated`: the file is exactly what Madness Desktop installed, and the
 *   built-in has moved on since — safe to replace.
 * - `customized`: the file has been edited since it was installed; replacing
 *   it would throw those edits away.
 *
 * Without an install-time hash (older installations) an edit can't be told
 * apart from a stale copy, so any difference counts as `outdated`.
 */
export function classifyScript(
  fileHash: string,
  installedHash: string | undefined,
  builtinHash: string
): InstalledScriptStatus {
  if (fileHash === builtinHash) {
    return 'current'
  }
  if (installedHash === undefined || fileHash === installedHash) {
    return 'outdated'
  }
  return 'customized'
}

function scriptPaths(repoPath: string, script: HookScript) {
  const dDir = join(repoPath, '.githooks', `${script.hookType}.d`)
  return {
    enabled: join(dDir, `${script.id}.sh`),
    disabled: join(dDir, `${script.id}.sh.disabled`),
  }
}

/** The installed copy of a script — enabled or disabled — or null if absent. */
export async function readInstalledScript(
  repoPath: string,
  script: HookScript
): Promise<string | null> {
  const paths = scriptPaths(repoPath, script)
  for (const path of [paths.enabled, paths.disabled]) {
    if (await pathExists(path)) {
      return readFile(path, 'utf8')
    }
  }
  return null
}

/**
 * Replace the installed copy of a script, keeping it enabled or disabled as
 * it was. Returns the hash of what was written.
 */
export async function writeInstalledScript(
  repoPath: string,
  script: HookScript,
  text: string
): Promise<string> {
  const paths = scriptPaths(repoPath, script)
  const target = (await pathExists(paths.disabled))
    ? paths.disabled
    : paths.enabled
  await writeFile(target, text, { mode: 0o755 })
  await chmod(target, 0o755)
  return hashScript(text)
}
